### ISSUE TITLE
Suggestion: Switches to control how missing packages are handled

### ISSUE THREAD

**Issue by jonaskello** [whoeverest/wsrun#13]
This is a follow up suggestion for #10.

There could be a set of switches controlling how missing packages are handled:

`--error-missing`: This is the default and this switch does not need to be specified (and it doesn't even have to exist other than for documentation purposes). If a package is missing it will break with an error without running any of the packages. This is already the default so nothing has to be done (expect maybe add documentation).

`--warn-missing`: If a package is missing a warning will be printed but all packages that have the script will still be run. This is the same as the existing `--exclude-missing` (and it could of course keep that name). So it is already done.

`--ignore-missing`: This is the lerna/oao behaviour. If a package is missing it will be ignored without any warnings. This switch would need to be added.

I'm not generally fond of solving problems by adding more switches but I think most people coming from lerna/oao will want to have the `--ignore-missing` behaviour to feel at home and be able migrate to wsrun. Existing lerna users have already [voiced an opinion](https://github.com/yarnpkg/rfcs/pull/87#issuecomment-363671577) towards this in the yarn RFC.

If this would be an accepted approach I could work on a PR for this.

**Comment by spion** [comment]
Please don't open new issues. We can continue the discussion in #10

**Comment by jonaskello** [comment]
Yes, this suggestion is different than the one in #10 (which is about eliminating the warnings for --exclude-missing).  I thought it would be cleaner to have a separate issue, but sure, we can discuss this suggestion in #10 too.

I agree that adding more switches is not good (as I already stated in the original post in this issue). But since #10 has a wont-fix label and there seems to be no agreement, it could be argued that leaving lerna users without any migration option is worse than adding more switches.

**Comment by spion** [comment]
Lerna users are provided with a migration option, which warns that the behaviour is not desirable. The entire point of adding the `--exclude-missing` option is to support migrating lerna users without endorsing lerna's behaviour as acceptable or good.
