### ISSUE TITLE
Return exit code > 0 if command failed for any workspace

### ISSUE THREAD

**Issue by TimoSta** [whoeverest/wsrun#16]
Currently, exit code 1 is returned if option `--fast-exit` is set and the execution is ended prematurely due to the script returning an exit code > 0 for any of the workspaces.

However, if option `--fast-exit` is not set, wsrun always returns exit code 0.

From my perspective, this should be changed to always return exit code 1 if any of the scripts failed, independent of whether or not `--fast-exit` is set.

This behavior would be more consistent, especially considering that the current behavior is not documented for `--fast-exit`. It would also be beneficial in scenarios where wsrun should be chained with other commands and the exit code is used to decide on whether or not to continue execution.

Especially in combination with #15, this should be fairly trivial to implement, as we have all the necessary information available already.

How do you feel about this?

**Comment by mattfysh** [comment]
This is super-helpful if running something like linting on pre-commit

**Comment by spion** [comment]
Yup, sounds good. But we'll have to bump the version to 2.0 in case someone is relying on current behaviour.
