### ISSUE TITLE
yarnpgk version of the wsrun 2.1.0 tarball is bad.

### ISSUE THREAD

**Issue by krotscheck** [whoeverest/wsrun#20]
Upgrading to 2.1.0 broke my build. A bit of investigation showed that `workspaceGlobs` in `index.js` reads 'workspace' not 'workspaces', and doesn't include any of the changes in #18.
```
const workspaceGlobs = JSON.parse(fs.readFileSync('./package.json', 'utf8')).workspace || [
    'packages/*'
];
```

A bit more digging showed that the wsrun tarball in the yarn registry includes this change:
`wget https://registry.yarnpkg.com/wsrun/-/wsrun-2.1.0.tgz`

**Comment by spion** [comment]
2.1.1 should have the build of the latest sources

**Comment by krotscheck** [comment]
Confirmed, works again!
