### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by jevakallio** [whoeverest/wsrun#29]
Hi! Great project! At this time, I'm not able to use it in my project because it doesn't define any license terms, which is a legal requirement for most companies these days.

Please consider adding a permissive license (e.g. MIT).

GitHub makes this really easy:
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by whoeverest** [comment]
Thanks! Done, cheers. https://github.com/whoeverest/wsrun/blob/master/LICENSE
