### ISSUE TITLE
v3.0 breaks CLI package selection

### ISSUE THREAD

**Issue by ritave** [whoeverest/wsrun#33]
wsrun is often used as below:
```json
{
  "scripts": {
     "build": "wsrun build $PKG --fast-exit -r --stages"
   }
}
```
allowing for easy CLI selection of the package to build:
```PKG=my_package yarn build```

The introduction of parameter passing in v3 breaks that compatibility. That functionality was a sole reason that we've been using wsrun rather than lerna. It also breaks other projects such as https://github.com/0xProject/0x-monorepo

**Comment by spion-h4** [comment]
Yes, v3.0 is a backward incompatible change to allow argument passing

To select packages with wsrun 3.x and above, use `wsrun -p $PKG --fast-exit -r --stages build`
