### ISSUE TITLE
Parallel execution is broken in 3.x

### ISSUE THREAD

**Issue by krotscheck** [whoeverest/wsrun#34]
As per my comment on https://github.com/whoeverest/wsrun/commit/833e55143a9706488669df544460978a1b38d1fc, it appears that the `runOne` method, if mode === `parallel` reassigns the `finished` property, meaning the previous assignment of the promise chain that generates the CmdProcess instance is discarded / never executed.

**Comment by krotscheck** [comment]
Note that this is most obvious if you have a monorepo with a long-running set of parallel processes, such as a `chokidar` based watch/build cycle.

**Comment by spion** [comment]
Fixed in d961e0e07c07a03642b3c581bbdc95f5cec9e3e4 and published in v3.3.5
