### ISSUE TITLE
Maximum Concurrency option

### ISSUE THREAD

**Issue by ckknight** [whoeverest/wsrun#35]
It'd be useful to have an option to arbitrarily limit the amount of running scripts to a certain maximum, such as 5 or 10.

For the most part, I've been able to rely on `--stages` to prevent too much from happening at once, but with the introduction of one new package that has no inter-workspace dependencies, it has become too much for the CI server I'm using to handle.

**Comment by spion** [comment]
I'm thinking an environment variable would be nicer in this case, WSRUN_MAX_CONCURRENCY.

FYI this is the place in the code that controls this feature: 

https://github.com/whoeverest/wsrun/blob/master/src/run-graph.ts#L88

**Comment by ckknight** [comment]
I'd much prefer an argument over an environment variable, but I'd willing to accept both as options.

**Comment by ckknight** [comment]
Alright, made a PR for this for what I would want — feel free to alter and/or merge at your leisure.
