### ISSUE TITLE
Regression in 3.6.1: `wsrun clean` executes nothing

### ISSUE THREAD

**Issue by ckknight** [whoeverest/wsrun#37]
I have a repo with a top-level `package.json` that looks similar to this:

```json
{
  "name": "my-repo",
  "private": true,
  "workspaces": {
    "packages": [
      "backend/*",
      "common/*",
      "frontend/*"
    ]
  }
}
```

In 3.5.0, `wsrun clean` would appropriately execute on all workspaces within `backend`, `common`, and `frontend`.

In 3.6.1, `wsrun clean` does not execute a single command.

I suspect the issue is with https://github.com/whoeverest/wsrun/commit/a3503be5140b1455577b9c933c1f03f50608ee60, as the globs default to `['*']` when it should instead probably default to whatever `workspaces` within the top-level `package.json` specifies.

**Comment by spion** [comment]
Looks like this affected namespaced packages. Should be fixed with 3.6.2
