### ISSUE TITLE
Run cmd only if it is available in package

### ISSUE THREAD

**Issue by donaldpipowitch** [whoeverest/wsrun#5]
Thank you for this package. I want to use it as an alternative to Lerna. In Lerna "run <cmd>" only executes the command if it is available in `package.json:scripts[<cmd>]`. Can the same feature be added to this lib?

E.g. say I have 10 packages in my workspace, but only 8 have a `build` command in the `scripts` section of the `package.json`. I'd like to just call `$ yarn wsrun build --stages`  without the need to use `--exclude` for the other 2 packages.

**Comment by wh4everest** [comment]
Currently, wsrun doesn't parse the package.jsons of the workspace packages, instead just do: `cd packages && <bin> <cmd>` where the default `<bin>` is "yarn"

We could adopt a different approach, where it would parse the package/package.json and execute the script, if defined.

@spion thoughts?

**Comment by wh4everest** [comment]
Actually, I'm talking nonsense. We're parsing the package.json to extract the dependencies. We could also extract scripts and not run if script name is not present.

**Comment by donaldpipowitch** [comment]
That would be awesome.

**Comment by spion** [comment]
`--skip-missing` sounds like a good option, I just wonder if thats the good default

p.s. --fast-exit should probably be the default

**Comment by donaldpipowitch** [comment]
> I just wonder if thats the good default

At least Lerna, which is AFAIK the most popular tool in this place, does it by default. I "think" bolt does it that way as well.

**Comment by spion** [comment]
Interesting, I didn't know there is a RFC for this in yarn.

To me, yarn doing the heavy lifting of installing and cross-linking all dependencies within a workspace is sufficient. The rest can be done using custom packages.

We plan on making another package that deals with sub-repository management only, based on the git functionality of Marijn's prosemirror tool: https://github.com/ProseMirror/prosemirror/blob/master/bin/pm.js#L47

**Comment by spion** [comment]
Added --exclude-missing

**Comment by donaldpipowitch** [comment]
Thank you _very_ much!
