### ISSUE TITLE
Suggestion: Skip <cmd> if it does not exist for a package

### ISSUE THREAD

**Issue by jonaskello** [whoeverest/wsrun#8]
For example, I have 6 packages, but only 2 have the "start" cmd in the scripts section of package.json. I would like to do `yarn wsrun start` to start them, but I then get failures for the other 4 packages. 

Perhaps it would be possible to pre-check in the package.json of each package and skip the ones that does not have the specified cmd specified?

**Comment by spion** [comment]
The option is called `--exclude-missing`. From the readme:

```
--exclude-missing               skip packages which lack the specified script
```

**Comment by jonaskello** [comment]
Thanks, that's perfect! Don't know how I could have missed that in the docs :-).
